import React,{useState,useEffect}from"react";
const API="http://192.168.100.4:5000/api";
const inp={width:"100%",padding:"10px",marginBottom:12,borderRadius:8,border:"1px solid #333",background:"#0a0a1a",color:"#fff",boxSizing:"border-box"};
function btn(c){return{background:c,color:"#fff",border:"none",borderRadius:8,padding:"8px 16px",cursor:"pointer",marginLeft:8};}
function Login({setToken,setUser,setPage}){
const[email,setEmail]=useState("");
const[pass,setPass]=useState("");
const[err,setErr]=useState("");
const go=async()=>{try{const r=await fetch(API+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password:pass})});const d=await r.json();if(d.token){localStorage.setItem("token",d.token);setToken(d.token);setUser(d.user);setPage("home");}else setErr(d.error||"Failed");}catch(e){setErr("Connection failed");}};
return(<div style={{minHeight:"100vh",background:"#0a0a1a",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{background:"#1a1a2e",padding:40,borderRadius:16,width:300}}><h2 style={{color:"#00d4ff",textAlign:"center"}}>Login</h2>{err&&<p style={{color:"#e91e63"}}>{err}</p>}<input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} style={inp}/><input placeholder="Password" type="password" value={pass} onChange={e=>setPass(e.target.value)} style={inp}/><button onClick={go} style={{...btn("#00d4ff"),width:"100%",marginLeft:0,padding:"12px"}}>Login</button><p style={{textAlign:"center",color:"#888"}}>No account? <span onClick={()=>setPage("register")} style={{color:"#00d4ff",cursor:"pointer"}}>Register</span></p></div></div>);}
function Register({setToken,setUser,setPage}){
const[form,setForm]=useState({name:"",email:"",phone:"",password:""});
const[err,setErr]=useState("");
const go=async()=>{try{const r=await fetch(API+"/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(d.token){localStorage.setItem("token",d.token);setToken(d.token);setUser(d.user);setPage("home");}else setErr(d.error||"Failed");}catch(e){setErr("Connection failed");}};
return(<div style={{minHeight:"100vh",background:"#0a0a1a",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{background:"#1a1a2e",padding:40,borderRadius:16,width:300}}><h2 style={{color:"#00c853",textAlign:"center"}}>Register</h2>{err&&<p style={{color:"#e91e63"}}>{err}</p>}{["name","email","phone","password"].map(f=>(<input key={f} placeholder={f.charAt(0).toUpperCase()+f.slice(1)} type={f==="password"?"password":"text"} value={form[f]} onChange={e=>setForm({...form,[f]:e.target.value})} style={inp}/>))}<button onClick={go} style={{...btn("#00c853"),width:"100%",marginLeft:0,padding:"12px"}}>Register</button><p style={{textAlign:"center",color:"#888"}}>Have account? <span onClick={()=>setPage("login")} style={{color:"#00d4ff",cursor:"pointer"}}>Login</span></p></div></div>);}
function Admin({token,setPage}){
const[stats,setStats]=useState(null);
useEffect(()=>{fetch(API+"/admin/stats",{headers:{Authorization:"Bearer "+token}}).then(r=>r.json()).then(setStats).catch(()=>{});},[]);
return(<div style={{minHeight:"100vh",background:"#0a0a1a",color:"#fff",padding:20}}><div style={{maxWidth:800,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h1 style={{color:"#7b2ff7"}}>Admin Dashboard</h1><button onClick={()=>setPage("home")} style={btn("#555")}>Back</button></div>{stats&&(<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(180px, 1fr))",gap:15,marginTop:20}}>{[["Total Users",stats.totalUsers,"#00d4ff"],["Active Sessions",stats.activeSessions,"#00c853"],["Transactions",stats.totalTransactions,"#7b2ff7"],["Total Revenue","UGX "+(stats.totalRevenue||0).toLocaleString(),"#ff6d00"],["Today","UGX "+(stats.todayRevenue||0).toLocaleString(),"#e91e63"]].map(([l,v,c])=>(<div key={l} style={{background:"#1a1a2e",border:"2px solid "+c,borderRadius:12,padding:20,textAlign:"center"}}><p style={{color:c,margin:"0 0 8px",fontSize:13}}>{l}</p><p style={{fontSize:28,fontWeight:"bold",margin:0}}>{v}</p></div>))}</div>)}</div></div>);}
function Payment({token,plan,user,onBack}){
const[phone,setPhone]=useState(user.phone||"");
const[provider,setProvider]=useState("mtn");
const[status,setStatus]=useState("idle");
const[msg,setMsg]=useState("");
const go=async()=>{
setStatus("loading");setMsg("Sending payment request...");
try{const r=await fetch(API+"/payments/initiate",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({planId:plan._id,phone,provider})});
const d=await r.json();
if(d.internalId){setStatus("polling");setMsg("Check your phone and approve the payment...");let a=0;const iv=setInterval(async()=>{a++;if(a>20){clearInterval(iv);setStatus("error");setMsg("Timed out");return;}try{const r2=await fetch(API+"/payments/status/"+d.internalId,{headers:{Authorization:"Bearer "+token}});const d2=await r2.json();if(d2.status==="success"){clearInterval(iv);setStatus("success");setMsg("Payment successful!");}if(d2.status==="failed"){clearInterval(iv);setStatus("error");setMsg("Payment failed: "+(d2.reason||"Unknown"));}}catch(e){}},3000);}
else{setStatus("error");setMsg(d.error||"Payment failed");}}catch(e){setStatus("error");setMsg("Connection failed");}};
return(<div style={{minHeight:"100vh",background:"#0a0a1a",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div style={{background:"#1a1a2e",padding:40,borderRadius:16,width:340}}><h2 style={{color:plan.color,textAlign:"center"}}>{plan.name}</h2><p style={{textAlign:"center",fontSize:24,fontWeight:"bold",color:plan.color}}>UGX {plan.price.toLocaleString()}</p>{status==="idle"&&(<><label style={{color:"#888",fontSize:13}}>Phone Number</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="07XXXXXXXX" style={inp}/><label style={{color:"#888",fontSize:13}}>Payment Method</label><div style={{display:"flex",gap:10,marginBottom:15}}><button onClick={()=>setProvider("mtn")} style={{...btn(provider==="mtn"?"#ffd700":"#333"),flex:1,marginLeft:0}}>MTN MoMo</button><button onClick={()=>setProvider("airtel")} style={{...btn(provider==="airtel"?"#e91e63":"#333"),flex:1,marginLeft:0}}>Airtel Money</button></div><button onClick={go} style={{...btn(plan.color),width:"100%",marginLeft:0,padding:"12px"}}>Pay Now</button><button onClick={onBack} style={{...btn("#555"),width:"100%",marginLeft:0,padding:"10px",marginTop:10}}>Back</button></>)}{status==="loading"&&<p style={{textAlign:"center",color:"#00d4ff"}}>{msg}</p>}{status==="polling"&&<div style={{textAlign:"center"}}><p style={{color:"#ffd700"}}>{msg}</p><p style={{color:"#888",fontSize:13}}>Checking...</p></div>}{status==="success"&&<div style={{textAlign:"center"}}><p style={{color:"#00c853",fontSize:20}}>Payment Successful!</p><p style={{color:"#888"}}>Your WiFi is now active.</p><button onClick={onBack} style={{...btn("#00c853"),marginLeft:0,padding:"12px"}}>Done</button></div>}{status==="error"&&<div style={{textAlign:"center"}}><p style={{color:"#e91e63"}}>{msg}</p><button onClick={()=>setStatus("idle")} style={{...btn("#e91e63"),marginLeft:0,padding:"10px"}}>Try Again</button><button onClick={onBack} style={{...btn("#555"),marginLeft:0,padding:"10px",marginTop:10}}>Back</button></div>}</div></div>);}
export default function App(){
const[user,setUser]=useState(null);
const[token,setToken]=useState(localStorage.getItem("token"));
const[page,setPage]=useState("home");
const[plans,setPlans]=useState([]);
const[buying,setBuying]=useState(null);
useEffect(()=>{if(token){fetch(API+"/auth/me",{headers:{Authorization:"Bearer "+token}}).then(r=>r.json()).then(u=>{if(u&&u._id)setUser(u);else{localStorage.removeItem("token");setToken(null);}}).catch(()=>{});}fetch(API+"/plans").then(r=>r.json()).then(setPlans).catch(()=>{});},[token]);
const logout=()=>{localStorage.removeItem("token");setToken(null);setUser(null);setPage("home");};
if(page==="login")return<Login setToken={setToken} setUser={setUser} setPage={setPage}/>;
if(page==="register")return<Register setToken={setToken} setUser={setUser} setPage={setPage}/>;
if(page==="admin"&&user&&user.role==="admin")return<Admin token={token} setPage={setPage}/>;
if(buying)return<Payment token={token} plan={buying} user={user} onBack={()=>setBuying(null)}/>;
return(<div style={{minHeight:"100vh",background:"#0a0a1a",color:"#fff",fontFamily:"sans-serif",padding:20}}><div style={{maxWidth:800,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:30}}><h1 style={{color:"#00d4ff",margin:0}}>Adelian Ecstasy WiFi</h1><div>{user?(<span><span style={{marginRight:15}}>{user.name}</span>{user.role==="admin"&&<button onClick={()=>setPage("admin")} style={btn("#7b2ff7")}>Admin</button>}<button onClick={logout} style={btn("#e91e63")}>Logout</button></span>):(<span><button onClick={()=>setPage("login")} style={btn("#00d4ff")}>Login</button><button onClick={()=>setPage("register")} style={btn("#00c853")}>Register</button></span>)}</div></div><h2>Available Plans</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(200px, 1fr))",gap:15}}>{plans.map(p=>(<div key={p._id} style={{background:"#1a1a2e",border:"2px solid "+p.color,borderRadius:12,padding:20,textAlign:"center"}}><h3 style={{color:p.color,margin:"0 0 10px"}}>{p.name}</h3><p style={{margin:"5px 0"}}>Data: {p.data}</p><p style={{margin:"5px 0"}}>Speed: {p.speed}</p><p style={{margin:"5px 0"}}>Duration: {p.duration}</p><p style={{fontSize:24,fontWeight:"bold",color:p.color}}>UGX {p.price.toLocaleString()}</p>{user?<button onClick={()=>setBuying(p)} style={btn(p.color)}>Buy Now</button>:<button onClick={()=>setPage("login")} style={btn(p.color)}>Login to Buy</button>}</div>))}</div>{!user&&<p style={{textAlign:"center",marginTop:30,color:"#888"}}>Login or register to purchase a plan</p>}</div></div>);}